//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarioFutbol.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class JuegosJugadores
    {
        public int JuegosJugadoresID { get; set; }
        public int JuegoID { get; set; }
        public int JugadorID { get; set; }
        public bool EsLocal { get; set; }
    }
}
